# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fridayui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 693)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-30, -20, 1441, 791))
        self.label.setStyleSheet("border-radius:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../gif/back.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -10, 1391, 721))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../gif/border.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 50, 661, 371))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../gif/gif9.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 110, 451, 331))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../gif/gif6.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(920, 60, 401, 591))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../gif/robo.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 50, 180, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../gif/border.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(260, 50, 145, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../gif/border.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(70, 60, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white\n")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(270, 60, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Stencil")
        font.setPointSize(16)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white\n")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(420, 470, 541, 361))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../gif/gif1.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(50, 380, 361, 321))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../gif/gif10.gif"))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(550, 420, 291, 151))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../gif/lis.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)

        
        self.movie = QtGui.QMovie("../gif/back.jpg")
        self.label.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/border.png")
        self.movie.setSpeed(500)
        self.label_2.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/gif9.gif")
        self.movie.setSpeed(500)
        self.label_3.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/gif6.gif")
        self.label_4.setMovie(self.movie)
        self.movie.start()

        
        self.movie = QtGui.QMovie("../gif/robo.gif")
        self.movie.setSpeed(1000)
        self.label_5.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/gif1.gif")
        self.movie.setSpeed(50)
        self.label_6.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/gif10.gif")
        self.movie.setSpeed(50)
        self.label_9.setMovie(self.movie)
        self.movie.start()

        self.movie = QtGui.QMovie("../gif/lis.gif")
        self.movie.setSpeed(1000)
        self.label_10.setMovie(self.movie)
        self.movie.start()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
